// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkNrN7KcvJsKfucO6l-9qYx9l52S3qNeQ',
    appId: '1:184887830049:web:1009e26c905fbfcecda560',
    messagingSenderId: '184887830049',
    projectId: 'cleantrack-4c92b',
    authDomain: 'cleantrack-4c92b.firebaseapp.com',
    storageBucket: 'cleantrack-4c92b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDBuphtZcdXPJlRy-_QaLWWR3NxuL3W6E',
    appId: '1:184887830049:android:e9b4e7ea27b3d7c0cda560',
    messagingSenderId: '184887830049',
    projectId: 'cleantrack-4c92b',
    storageBucket: 'cleantrack-4c92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJnxK_Yv3pdTKbXAnADAnOykkgrqT2ew',
    appId: '1:184887830049:ios:60a120afc7975985cda560',
    messagingSenderId: '184887830049',
    projectId: 'cleantrack-4c92b',
    storageBucket: 'cleantrack-4c92b.firebasestorage.app',
    iosBundleId: 'com.example.cleantrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkJnxK_Yv3pdTKbXAnADAnOykkgrqT2ew',
    appId: '1:184887830049:ios:60a120afc7975985cda560',
    messagingSenderId: '184887830049',
    projectId: 'cleantrack-4c92b',
    storageBucket: 'cleantrack-4c92b.firebasestorage.app',
    iosBundleId: 'com.example.cleantrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkNrN7KcvJsKfucO6l-9qYx9l52S3qNeQ',
    appId: '1:184887830049:web:6a2e259384096f97cda560',
    messagingSenderId: '184887830049',
    projectId: 'cleantrack-4c92b',
    authDomain: 'cleantrack-4c92b.firebaseapp.com',
    storageBucket: 'cleantrack-4c92b.firebasestorage.app',
  );
}
